---
title: "DRiDO Figure 4"
author: "Johanna Fleischman"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide 
---

# Setup 

## Install Packages

```{r, message=F, warning=F}
suppressMessages(library(here))
suppressMessages(library(patchwork))
suppressMessages(library(ggrepel))
suppressMessages(library(RColorBrewer))
suppressMessages(library(tidyverse))
suppressMessages(library(clusterProfiler))
suppressMessages(library(org.Mm.eg.db))
suppressMessages(library(rrvgo))

knitr::opts_chunk$set(echo = TRUE, eval = TRUE, out.height = "100%", out.width = "100%", warning = F, message = F)
```

## Assign filepaths

```{r}
# set
local_filepath <- here::here() # "~/drido-multiomic-paper"

source(file.path(local_filepath, "R/statistics_functions.R"))
source(file.path(local_filepath, "R/figure_functions.R"))

lm_res_file <- "inst/extdata/20250417-Linear-MM-Age-Diet-Results.Rds"
lipidomics_data <- "inst/extdata/20250128-Normalized-Lipidomics-Data.Rds"
metabolomics_data <- "inst/extdata/20250128-Normalized-Metabolomics-Data.Rds"
proteomics_data <- "inst/extdata/20250129-Normalized-Proteomics-Data.Rds"
phenotype_data <- "inst/extdata/DOCR_Phenotype_Data.csv"
pll_lm_res_file <- "inst/extdata/20250424-Linear-MM-PLL-Aging-Results.Rds" # not scaled
pll_lm_res_phys_file <- "inst/extdata/20250528-Linear-MM-PLL-Aging-Phenotype-Results.Rds" # scaled result
pll_gam_summary_file <- "inst/extdata/20251008-PLL-GAM-Summary-Data.Rds"
name_conv_file <- "inst/supp_tables/Table_S1_CompoundAnnotations.csv"
physio_key_file <- "data/physio-key.csv"

# Mediation analysis - last 15% of life removed, needs filtering down to year 2
diet_med_analysis <- readRDS(file.path(local_filepath, "inst/extdata/20260310-Mediation-Sobel-Test-Summary-BW-Adj.Rds"))

# Mediation results for all molecular relationships. Columns not used to generate
# figures have been removed from file as it was generated from mediation-parse-all-features.R
# All columns necessary for computation are maintained in this file
# File is pre-filtered to sobel_p > 0.05 for size
molecular_med_results <- readRDS(file.path(local_filepath, "inst/extdata/20251024-Mediation-Sobel-Test-ALL-Mol-Ints-Reduced.Rds"))

# lasso predictive analysis
# 5000 boots, PLL > 85% removed (year 2 only)
lasso_results <- readRDS(file.path(local_filepath, "inst/extdata/20251114_LassoCalcs_Alpha1_Nboot5000.Rds"))
lasso_coef <- readRDS(file.path(local_filepath, "inst/extdata/20251012_LassoCoefs_Alpha1_Nboot5000.Rds"))
```

## Assign Constants

```{r}
sobel_p_threshold <- 0.01 # mediation adjusted p-value threshold
nboot <- 5000 # how many bootstraps were run
pll_thresh <- 1 # PLL cutoff for physiological correlations
span <- 0.5 # loess span for elbow selection of lasso traits to visualize
```

## Load and Clean Data

```{r}
# Read in analyses
lm_res <- readRDS(file.path(local_filepath, lm_res_file))

# get keys
name_conversion_use <- read.csv(file.path(local_filepath, name_conv_file)) %>%
  dplyr::select(name_use, feature_id)
physio_key <- read.csv(file.path(local_filepath, physio_key_file), header = TRUE)

# Make final DO-CR raw data frame
# Retains pre-diet intervention data
data_use <- docr_make_final_data(
  metabolomics_data_filepath = file.path(local_filepath, metabolomics_data),
  proteomics_data_filepath = file.path(local_filepath, proteomics_data),
  lipidomics_data_filepath = file.path(local_filepath, lipidomics_data),
  phenotype_data_filepath = file.path(local_filepath, phenotype_data),
  name_conversion_key = name_conversion_use
)

# Make LMM pretty
lm_res_pretty <- lm_res %>%
  dplyr::left_join(., name_conversion_use, by = "feature_id") %>%
  dplyr::filter(!is.na(name_use)) %>%
  dplyr::select(feature_id, name_use, model_term, model, coef, p_value_coef, padj, modality) %>%
  dplyr::mutate(
    model = make_names_pretty(model),
    model_term = make_names_pretty(model_term)
  ) %>%
  dplyr::mutate(Significant = ifelse(padj < 1e-3 & abs(coef) > 0.5, "Yes", "No")) %>%
  dplyr::mutate(
    Platform = stringr::str_to_title(modality),
    Platform = factor(Platform, levels = c("Metabolomics", "Lipidomics", "Proteomics"))
  )

# Get PLL aging model for heatmap
pll_lm_aging <- readRDS(file.path(local_filepath, pll_lm_res_file)) %>%
  dplyr::select(-method, compoundName) %>%
  dplyr::bind_rows(readRDS(file.path(local_filepath, pll_lm_res_phys_file)))

pll_gam_summaries <- readRDS(file.path(local_filepath, pll_gam_summary_file))
pll_gam_cluster_identities <- pll_gam_summaries %>%
  dplyr::distinct(trait, cluster)

# Molecular mediation model
molecular_med_results_clean_p <- molecular_med_results %>%
  dplyr::mutate(
    modality =
      dplyr::case_when(
        grepl("\\.M012|\\.M013", intervention_var) ~ "metabolomics",
        grepl("\\.M014|\\.M015", intervention_var) ~ "lipidomics",
        TRUE ~ "proteomics"
      )
  ) %>%
  dplyr::left_join(
    name_conversion_use %>%
      dplyr::rename(mediation_var = feature_id),
    by = "mediation_var"
  ) %>%
  dplyr::rename(name_use_mediator = name_use) %>%
  dplyr::left_join(
    name_conversion_use %>%
      dplyr::rename(intervention_var = feature_id),
    by = "intervention_var"
  ) %>%
  dplyr::rename(name_use_exposure = name_use)

molecular_med_results_clean <- molecular_med_results_clean_p %>%
  dplyr::filter(
    prop_mediated > 0 & prop_mediated < 1,
    !is.na(name_use_exposure)
  ) %>%
  as.data.frame() %>%
  dplyr::select(-mediation_var, -intervention_var)

# Diet Mediator Model
diet_med_analysis_clean <- diet_med_analysis %>%
  dplyr::inner_join(name_conversion_use, by = "feature_id") %>%
  dplyr::rename(name_use_mediator = name_use) %>%
  dplyr::mutate(diet = gsub("diet", "", model_term)) %>%
  dplyr::filter(
    !is.na(name_use_mediator),
    prop_mediated > 0 & prop_mediated < 1
  ) %>%
  as.data.frame()

# Lasso model
lasso_results_clean <- lasso_results %>%
  dplyr::mutate(feature_id = gsub("^`|`$", "", variable)) %>%
  dplyr::inner_join(name_conversion_use, by = "feature_id") %>%
  dplyr::mutate(
    coxph_pvalue = if ("coxph_pvalue" %in% names(.)) dplyr::coalesce(coxph_pvalue, 1) else 1
  )

lasso_coef_clean <- lasso_coef %>%
  t() %>%
  as.data.frame() %>%
  tibble::rownames_to_column("feature_id") %>%
  dplyr::mutate(feature_id = gsub("`|`$", "", feature_id)) %>%
  dplyr::inner_join(name_conversion_use, by = "feature_id") %>%
  tidyr::pivot_longer(
    cols = -c("feature_id", "name_use"),
    names_to = "model_id",
    values_to = "coef"
  ) %>%
  dplyr::group_by(name_use, feature_id) %>%
  dplyr::summarise(
    median_coef_nonzero = abs(median(coef[coef != 0])),
    mean_coef_all = abs(mean(coef)),
    per_selection = sum(coef != 0) / nboot,
    .groups = "drop"
  )
```

# Data Cleanup

## Figure S3B: Lasso Diagnostics

```{r, fig.width = 5, fig.height = 5}
per_select_thresh <- docr_find_elbow_smooth(lasso_coef_clean, "per_selection", "mean_coef_all", span = span)

# Quick diagnostic plot
x_seq <- seq(min(lasso_coef_clean$per_selection),
  max(lasso_coef_clean$per_selection),
  length.out = 500
)
fit <- loess(mean_coef_all ~ per_selection, data = lasso_coef_clean, span = span)
plot(lasso_coef_clean$per_selection, lasso_coef_clean$mean_coef_all,
  xlab = "Percent Selection", ylab = "Mean Absolute Coefficient"
)
lines(x_seq, predict(fit, newdata = data.frame(per_selection = x_seq)), col = "red")
abline(v = per_select_thresh, col = "blue", lty = 2)
text(
  x = per_select_thresh, y = max(lasso_coef_clean$mean_coef_all),
  labels = round(per_select_thresh, 3), col = "blue", adj = c(-0.1, 1)
)
```

## Get Names

```{r}
# molecular mediators are selected beneath pre-defined FDR threshold
mol_med_names <- molecular_med_results_clean %>%
  dplyr::filter(sobel_p_adj < sobel_p_threshold) %>%
  dplyr::pull(name_use_mediator)

# lasso predictors are selected at elbow of selection plot
lasso_names <- lasso_coef_clean %>%
  dplyr::filter(per_selection > per_select_thresh) %>%
  dplyr::pull(name_use)

mol_names <- mol_med_names %>%
  union(lasso_names) %>%
  unique()
```

### Tables: S6-8

```{r}
# Table S6 for publication generated from non-reduced file
table_s6 <- molecular_med_results_clean %>%
  dplyr::rename(
    Exposure = "name_use_exposure",
    Mediator = "name_use_mediator",
    Outcome = "outcome_var",
    FDR = "sobel_p_adj",
    Sobel_Pvalue = "sobel_p",
    Proportion_Mediated = "prop_mediated"
  ) %>%
  dplyr::mutate(Outcome = "Survival_Years") %>%
  dplyr::select(Exposure, Mediator, Outcome, FDR, Sobel_Pvalue, Proportion_Mediated, everything(), -modality)

# write.csv(table_s6,
#           file.path(local_filepath, "supplemental_tables_final", "Table_S6_Molecular_Mediation.csv"),
#           row.names = FALSE)

table_s7 <- diet_med_analysis_clean %>%
  dplyr::rename(
    Exposure = "model_term",
    Mediator = "name_use_mediator",
    Outcome = "outcome_var",
    FDR = "sobel_p_adj",
    Sobel_Pvalue = "sobel_p",
    Proportion_Mediated = "prop_mediated"
  ) %>%
  dplyr::mutate(Outcome = "Survival_Years") %>%
  dplyr::select(
    Exposure, Mediator, Outcome, FDR, Sobel_Pvalue, Proportion_Mediated, everything(),
    -modality, -feature_id, -diet, -age_years
  )

# write.csv(table_s7,
#           file.path(local_filepath, "supplemental_tables_final", "Table_S7_Diet_Mediation.csv"),
#           row.names = FALSE)

table_s8 <- lasso_coef_clean %>%
  dplyr::left_join(lasso_results_clean,
    by = c("feature_id", "name_use", "per_selection")
  ) %>%
  dplyr::select(
    -variable, -feature_id, -ci_significant, -z_scores,
    -zscore_pvalue, -median_coef_nonzero
  ) %>%
  dplyr::rename(
    Compound = "name_use",
    N_Selection = "n_selection",
    Percent_Selection = "per_selection",
    Mean_Coefficient = "mean_coef_all",
    Mean_Coefficient_SE = "se_coefs",
    Ci_95_Low = "ci_lower",
    Ci_95_High = "ci_upper",
    Point_Estimate = "coef_estimate",
    Point_Estimate_Pvalue = "coxph_pvalue"
  )

# write.csv(table_s8,
#           file.path(local_filepath, "supplemental_tables_final", "Table_S8_Lasso_CoxPh_Summary.csv"),
#           row.names = FALSE)
```

# Figure 4 Panels

## A: Heatmap

```{r, fig.width = 2.5, fig.height = 3.6}
# unite data
all_temp_heatmap <- dplyr::bind_rows(
  # PLL DA data
  pll_lm_aging %>%
    dplyr::filter(grepl("PLL", model_term)) %>%
    dplyr::mutate(
      model_term_group = "PLL",
      model_term = dplyr::case_when(grepl("PLL", model_term) ~ "PLL Aging")
    ) %>%
    dplyr::select(model_term, model_term_group, padj, coef, modality, feature_id),

  # Diet data
  lm_res_pretty %>%
    dplyr::filter(
      model_term %in% docr_get_diet_terms(),
      model == "Compound ~ Age + Diet + Bodyweight + Fasting + (1|Mouse)"
    ) %>%
    dplyr::mutate(model_term_group = "Diet") %>%
    dplyr::select(model_term, model_term_group, padj, coef, modality, feature_id)
) %>%
  # Filter on compounds and assign pretty names
  dplyr::left_join(., name_conversion_use, by = "feature_id") %>%
  dplyr::filter(
    !is.na(name_use),
    name_use %in% mol_names
  ) %>%
  dplyr::mutate(model_term = factor(model_term, levels = c("PLL Aging", docr_get_diet_terms()))) %>%
  dplyr::mutate(sig_symbol = dplyr::case_when(
    padj < 0.001 ~ "\u00B7\u00B7\u00B7",
    padj < 0.01 ~ "\u00B7\u00B7",
    padj < 0.05 ~ "\u00B7",
    TRUE ~ ""
  ))

# get clustering from pheatmap
ph <- docr_pheatmap(all_temp_heatmap,
  y_axis_var = "name_use",
  cluster_rows = TRUE,
  silent = TRUE
)
clustered_row_names <- all_temp_heatmap$name_use[ph$tree_row$order]

# apply to ggplot data
all_temp_heatmap <- all_temp_heatmap %>%
  dplyr::mutate(name_use = factor(name_use, levels = rev(clustered_row_names)))

hm <- ggplot2::ggplot(
  all_temp_heatmap,
  aes(
    x = model_term,
    y = name_use
  )
) +
  geom_tile(aes(fill = coef)) +
  geom_text(aes(label = sig_symbol),
    size = 3
  ) +
  facet_wrap(~"PLL Aging and\nDiet Coefficients") +
  docr_ggplot_theme(legend_position = "bottom") +
  labs(
    y = NULL,
    x = NULL,
    fill = "Linear Model Coefficient"
  ) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  scale_fill_gradient2(
    low = "#21336B", mid = "white", high = "#D63B24",
    midpoint = 0
  ) +
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5))
```

## B: Molecular Mediation

```{r, fig.width = 3, fig.height = 3.6}
# molecular mediators
all_mediator_res <- molecular_med_results_clean %>%
  dplyr::filter(
    name_use_mediator %in% clustered_row_names,
    sobel_p_adj < sobel_p_threshold
  ) %>%
  dplyr::mutate(name_use_y_axis = factor(name_use_mediator,
    levels =
      rev(clustered_row_names)
  )) %>%
  tidyr::complete(name_use_y_axis)

mediator_colors <- setNames(
  rep("grey50", length(clustered_row_names)),
  clustered_row_names
)
mediator_colors["VCAM1"] <- "#D55E00"
mediator_colors["SODE"] <- "#0072B2"

med_plot <- ggplot2::ggplot(
  all_mediator_res,
  aes(
    y = name_use_y_axis,
    x = prop_mediated,
    size = -log10(sobel_p_adj),
    color = name_use_mediator
  )
) +
  ggplot2::geom_point(
    shape = 21,
    fill = NA,
    stroke = 0.6
  ) +
  scale_color_manual(values = mediator_colors, guide = "none") +
  labs(
    x = "Proportion Mediated\n(Indirect / Total Effect)",
    y = ""
  ) +
  docr_ggplot_theme(legend_position = "bottom") +
  scale_size_continuous(name = expression("-log"[10] * "(Sobel P)"), range = c(0.1, 4)) +
  theme(
    legend.key.size = unit(0.4, "cm"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  ) +
  facet_wrap(~"Significant as\nMolecular Mediator") +
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 0.5))
```

## C: Lasso

```{r, fig.width = 2.5, fig.height = 3}
per_selection_red <- 0.80

lasso_coef_boxplot <- lasso_coef %>%
  t() %>%
  as.data.frame() %>%
  tibble::rownames_to_column("feature_id") %>%
  dplyr::mutate(feature_id = gsub("^`|`$", "", feature_id)) %>%
  dplyr::inner_join(name_conversion_use, by = "feature_id") %>%
  tidyr::pivot_longer(
    cols = -c("feature_id", "name_use"),
    names_to = "model_id",
    values_to = "coef"
  ) %>%
  dplyr::left_join(lasso_results_clean,
    by = c("name_use", "feature_id")
  ) %>%
  dplyr::filter(name_use %in% clustered_row_names) %>%
  dplyr::mutate(name_use = factor(name_use,
    levels =
      rev(clustered_row_names)
  )) %>%
  tidyr::complete(
    name_use = factor(clustered_row_names,
      levels = rev(clustered_row_names)
    ),
    fill = list(value = 0)
  ) %>%
  dplyr::mutate(group = ifelse(coxph_pvalue < 0.05 & per_selection > per_selection_red,
    "Sig",
    "Insig"
  ))

# box plot on coefficients
p1 <- ggplot2::ggplot(
  lasso_coef_boxplot,
  aes(
    y = name_use,
    x = coef,
    color = group
  )
) +
  ggplot2::geom_boxplot(
    outliers = FALSE,
    fill = NA,
    outlier.alpha = 0.2,
    outlier.fill = NA,
    outlier.shape = 21
  ) +
  docr_ggplot_line(x = 0) +
  labs(
    x = "All Coefficients\n(n = 5000)",
    y = ""
  ) +
  scale_color_manual(values = c(
    "Sig" = "#009E73",
    "Insig" = "grey80"
  )) +
  docr_ggplot_theme(legend_position = "none") +
  theme(
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    plot.margin = margin(t = 2, r = -10, b = 2, l = 1)
  ) +
  facet_wrap(~"Significant as\nSurvival Predictor")

lasso_filtered <- lasso_results_clean %>%
  dplyr::filter(name_use %in% clustered_row_names) %>%
  dplyr::mutate(name_use = factor(name_use,
    levels =
      rev(clustered_row_names)
  )) %>%
  tidyr::complete(
    name_use = factor(clustered_row_names,
      levels = rev(clustered_row_names)
    ),
    fill = list(value = 0)
  ) %>%
  dplyr::mutate(group = ifelse(coxph_pvalue < 0.05 & per_selection > per_selection_red,
    "Sig",
    "Insig"
  ))

# percent significant bars for right side
p2 <- ggplot2::ggplot(
  lasso_filtered,
  aes(
    y = name_use,
    x = per_selection * 100,
    size = -log10(coxph_pvalue),
    color = group,
    fill = group
  )
) +
  ggplot2::geom_col(width = 0.7) +
  labs(x = "", y = "") +
  scale_color_manual(values = c(
    "Sig" = "#009E73",
    "Insig" = "grey80"
  )) +
  scale_fill_manual(values = c(
    "Sig" = "#009E73",
    "Insig" = "grey80"
  )) +
  annotate("text",
    x = -10, y = length(clustered_row_names) + 0.8,
    label = "%\nSelection",
    size = 6 / ggplot2::.pt, hjust = 0, vjust = -0.35
  ) +
  scale_x_continuous(breaks = c(0, per_selection_red * 100)) +
  docr_ggplot_line(x = per_selection_red * 100) +
  docr_ggplot_theme(legend_position = "none") +
  coord_cartesian(clip = "off") +
  theme(
    axis.text.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  ) +
  theme(plot.margin = margin(t = 2, r = 5, b = 2, l = -10))
```

## ABC: Combined Plot

```{r, fig.height = 4.5, fig.width = 5.5}
comb_plot <- hm + med_plot + p1 + p2 +
  patchwork::plot_layout(
    nrow = 1,
    widths = c(2.5, 2.5, 2.5, 0.55),
    guides = "collect"
  ) &
  theme(legend.position = "bottom")
comb_plot

# docr_ggsave(plot_object = comb_plot,
#            paste0("Fig_4A_ALL"),
#            plot_width = 5.5,
#            plot_height = 4.5,
#            local_filepath = local_filepath)
```

Figure 4D and related are printed out of lasso_analysis_script.R

## E: SODE and VCAM Exposures

```{r, fig.width = 1.6, fig.height = 6}
med_colors <- c(
  "VCAM1" = "#D55E00",
  "SODE" =  "#0072B2"
)

plot_data <- molecular_med_results_clean_p %>%
  as.data.frame() %>%
  dplyr::select(-mediation_var, -intervention_var) %>%
  dplyr::filter(
    !is.na(name_use_exposure),
    name_use_mediator %in% c("VCAM1", "SODE"),
    sobel_p_adj < sobel_p_threshold
  ) %>%
  dplyr::group_by(name_use_exposure) %>%
  dplyr::mutate(
    pm_se = prop_mediated * sqrt((sobel_se / indirect_effect)^2 + (total_se / total_effect)^2),
    membership = case_when(
      all(c("VCAM1", "SODE") %in% name_use_mediator) ~ "VCAM1 and SODE",
      all(name_use_mediator == "VCAM1") ~ "VCAM1 only",
      all(name_use_mediator == "SODE") ~ "SODE only"
    ),
    membership = factor(membership, levels = c("VCAM1 and SODE", "VCAM1 only", "SODE only")),
    prop_mediated_signed = if_else(a_coeff < 0,
      -abs(prop_mediated),
      abs(prop_mediated)
    ),
    sort_key = prop_mediated_signed
  ) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    name_use_exposure = reorder(name_use_exposure, sort_key)
  )


gg <- plot_data %>%
  ggplot(aes(
    y    = name_use_exposure,
    x    = prop_mediated_signed,
    fill = name_use_mediator
  )) +
  geom_col(alpha = 0.5) +
  geom_errorbarh(aes(
    xmin = prop_mediated_signed - pm_se,
    xmax = prop_mediated_signed + pm_se,
    color = name_use_mediator,
  ), height = 0.3, linewidth = 0.3) +
  geom_vline(xintercept = 0, linewidth = 0.4, color = "grey40") +
  geom_vline(
    xintercept = c(-1, 1), linetype = "dashed",
    linewidth = 0.3, color = "grey60"
  ) +
  scale_fill_manual(values = med_colors, name = NULL, guide = "none") +
  scale_color_manual(values = med_colors, name = NULL, guide = "none") +
  scale_x_continuous(
    labels = function(x) scales::percent(abs(x)),
    breaks = c(-1, 0, 1),
    name   = "Proportion mediated\nNegative             Positive\ncorrelation         correlation",
  ) +
  coord_cartesian(xlim = c(-1.6, 1.6)) +
  docr_ggplot_theme(x_text_angle = 0, x_text_hjust = 0.5) +
  scale_y_discrete(position = "right") +
  facet_grid(
    rows   = vars(membership),
    scales = "free_y",
    space  = "free_y",
    switch = "y"
  ) +
  theme(
    axis.text = element_text(size = 5),
    axis.title = element_text(size = 5),
    legend.position = "none",
    axis.text.y = element_text(size = 5),
    axis.text.y.right = element_text(size = 5),
    strip.text.y.left = element_text(
      size = 6, hjust = 0.5, angle = 90,
      margin = margin(2, 2, 2, 2)
    ),
    plot.title = element_text(margin = margin(b = 4)),
    panel.spacing = unit(2, "pt")
  ) +
  labs(title = "Mediation exposures\nof top predictors", y = NULL)

gg

# docr_ggsave(gg, "Fig_4E_Vcam1_Sod3", 6, 1.6, local_filepath = local_filepath)
```

# Supplement

## S3A: Diet Mediators

```{r, fig.width = 4, fig.height = 5}
# For supplement plot
diet_names <- diet_med_analysis_clean %>%
  dplyr::arrange(sobel_p_adj) %>%
  dplyr::slice_head(n = 40) %>% # around FDR < 0.25, pvalue < 0.015
  dplyr::pull(name_use_mediator) %>%
  unique()

diet_med_analysis_clean_plot <- diet_med_analysis_clean %>%
  dplyr::filter(name_use_mediator %in% diet_names) %>%
  dplyr::mutate(name_use_y_axis = factor(name_use_mediator,
    levels =
      rev(diet_names)
  )) %>%
  tidyr::complete(name_use_mediator) %>%
  dplyr::mutate(group = "Significant as\nDiet Mediator") %>%
  dplyr::mutate(Diet = paste0("Diet ", diet)) %>%
  dplyr::arrange(factor(Diet, levels = c(
    "Diet 1D",
    "Diet 2D",
    "Diet 20",
    "Diet 40"
  ))) %>%
  dplyr::mutate(sig_fill = ifelse(sobel_p_adj < 0.2, Diet, NA))

custom_colors <- c(
  "Diet 1D" = "skyblue",
  "Diet 2D" = "royalblue4",
  "Diet 20" = "orange",
  "Diet 40" = "firebrick"
)

med_plot <- ggplot2::ggplot(
  diet_med_analysis_clean_plot,
  aes(
    y = name_use_y_axis,
    x = prop_mediated,
    fill = sig_fill,
    color = Diet,
    size = -log10(sobel_p_adj)
  )
) +
  ggplot2::geom_point(shape = 21, stroke = 0.6) +
  labs(
    title = "Top 40 Diet-Lifespan Mediation Relationships by FDR",
    x = "Proportion Mediated\n(Indirect / Total Effect)", y = ""
  ) +
  docr_ggplot_theme(legend_position = "right") +
  scale_fill_manual(values = alpha(custom_colors, 0.5), na.value = NA) +
  scale_color_manual(name = "Diet", values = custom_colors) +
  scale_size_continuous(
    name = expression("FDR"),
    range = c(0.1, 4),
    breaks = c(-log10(0.5), -log10(0.2), -log10(0.1), -log10(0.01), -log10(0.001)),
    labels = c("0.5", "0.2", "0.1", "0.01", "0.001")
  ) +
  guides(
    fill = "none",
    color = guide_legend(override.aes = list(fill = NA, size = 3)),
    size = guide_legend(
      title = expression("FDR, filled ≤ 0.2"),
      override.aes = list(
        fill = c(NA, alpha("grey50", 0.5), alpha("grey50", 0.5), alpha("grey50", 0.5), alpha("grey50", 0.5)),
        color = "grey40"
      )
    )
  ) +
  theme(legend.key.size = unit(0.4, "cm")) +
  facet_wrap(~group)
med_plot
#
# docr_ggsave(plot_object = med_plot,
#            paste0("Fig_S5_Diet_Mediation"),
#            plot_width = 4,
#            plot_height = 5,
#            local_filepath = local_filepath)
```

## S4: Lifespan Correlation

```{r, fig.width = 2.35, fig.height = 4}
names_print <- lasso_results_clean %>%
  dplyr::filter(per_selection > 0.60) %>%
  dplyr::pull(name_use) %>%
  unique()
names_print <- names_print[names_print %in% mol_names]

for (nu in names_print) {
  data_use_temp <- data_use %>%
    dplyr::filter(
      name_use %in% nu,
      !is.na(trait_value),
      !is.na(days_remaining)
    )

  temp_label <- docr_facet_stats(data_use_temp,
    value_x = "days_remaining",
    value_y = "trait_value",
    facet_1 = "diet",
    facet_2 = "Age"
  )

  title <- bquote(.(nu) * ", Mean R"^2 ~ "=" ~
    .(round(mean(temp_label$r.squared), 3) * 100) * "%")

  if (nu %in% c("SODE", "CBPQ", "CFHR1")) {
    label_y <- -Inf
    label_vjust <- -0.15
  } else {
    label_y <- Inf
    label_vjust <- 1.3
  }

  g <- ggplot(
    data_use_temp,
    aes(x = days_remaining, y = trait_value, color = diet)
  ) +
    facet_grid(rows = vars(diet), cols = vars(Age), scales = "free") +
    labs(
      y = expression("Log"[2] * " Normalized Adbundance"),
      x = "Days of Life Remaining",
      title = title
    ) +
    geom_point(size = 0.3, alpha = 0.4) +
    scale_color_manual(name = "Diet", values = docr_get_diet_colors()) +
    geom_smooth(
      method = "lm", show.legend = FALSE, alpha = 0.8,
      linewidth = 0.5, formula = "y ~ x"
    ) +
    docr_ggplot_theme() +
    theme(
      text = element_text(size = 5),
      axis.text = element_text(size = 5),
      axis.title = element_text(size = 5),
      plot.title = element_text(size = 5),
      legend.text = element_text(size = 5),
      legend.title = element_text(size = 5),
      strip.text = element_text(size = 5, margin = margin(2, 2, 2, 2)),
      panel.spacing = unit(0.1, "lines")
    ) +
    docr_ggplot_stats_label(temp_label,
      y = label_y,
      vjust = label_vjust,
      size = 5 / ggplot2::.pt,
      color = "black"
    )
  print(g)

  # docr_ggsave(plot_object = g,
  #             paste0("Fig_S6_Lifespan_Corr_", nu),
  #             plot_width = 2.35,
  #             plot_height = 4,
  #             local_filepath = local_filepath)
}
```





