#' MS3 lipids library
#'
#' Returns DataFrame containing all ms3 lipid library information
#'
#' @param ms2_lib
#'     msp lipid library dataframe (can be generated by mzkitcpp::import_msp_lipids_library()).
#'
#' @export
to_ms3_lib <- function(ms2_lib) {
  # Case: input is a data frame.
  is_has_data_frame <- any(class(ms2_lib) == "data.frame")
  if (!is_has_data_frame) {
    stop("Input argument \"ms2_lib\" must be a data frame.\n
         This can be generated by calling mzkitcpp::import_msp_lipids_library(<file-path>).")
  }

  ms3_lib <- ms2_lib %>%
    dplyr::mutate(ref_ms2_mz_prec_str = stringr::str_extract(fragmentLabel, "ms3-\\{[0-9]+\\.[0-9]+\\}")) %>%
    dplyr::mutate(ref_ms2_mz_prec = ifelse(!is.na(ref_ms2_mz_prec_str), gsub("^ms3-\\{", "", ref_ms2_mz_prec_str), "")) %>%
    dplyr::mutate(ref_ms2_mz_prec = ifelse(!is.na(ref_ms2_mz_prec_str), gsub("\\}$", "", ref_ms2_mz_prec), "")) %>%
    dplyr::mutate(ref_ms2_mz_prec = ifelse(!is.na(ref_ms2_mz_prec_str), as.double(ref_ms2_mz_prec), NA)) %>%
    dplyr::filter(!is.na(ref_ms2_mz_prec)) %>%
    dplyr::mutate(prec_mzs = paste0("(", as.character(round(ref_ms1_mz, digits = 0)), ", ", as.character(round(ref_ms2_mz_prec, digits = 0)), ")")) %>%
    dplyr::rename(ref_ms3_mz = ref_ms2_mz) %>%
    dplyr::rename(ref_ms2_mz = ref_ms2_mz_prec) %>%
    dplyr::mutate(ms3_mz_str = as.character(round(ref_ms3_mz))) %>%
    dplyr::select(-ref_ms2_mz_prec_str) %>%
    dplyr::mutate(fragmentLabel = gsub("ms3-\\{[0-9]+\\.[0-9]+\\}[- ]?", "", fragmentLabel)) %>%
    dplyr::mutate(fragment_label_bits = stringr::str_split(fragmentLabel, "/")) %>%
    dplyr::mutate(fragmentLabel = sapply(fragment_label_bits, function(x) {
      x_u <- unique(x)
      x_u_s <- stringr::str_sort(x_u)
      paste(x_u_s, collapse = "/")
    })) %>%
    dplyr::select(-fragment_label_bits) %>%
    # return in reasonable order
    dplyr::select(
      lipidClass,
      compositionSummary,
      chainLengthSummary,
      molecularFormula,
      compoundMonoisotopicMass,
      compoundName,
      adductName,
      fragmentLabel,
      ref_ms1_mz,
      ref_ms2_mz,
      ref_ms3_mz,
      prec_mzs,
      ms3_mz_str
    )

  ms3_lib
}

#' MS2 lipids library
#'
#' Returns DataFrame containing all ms3 lipid library information formatted as an MS2 library
#'
#' @param ms3_lib
#'     msp lipid library dataframe formatted in ms3 format
#'     ms3 libraries can be created from ms2 libraries by clamr::to_ms3(ms2_lib)
#'
#' @export
to_ms2_lib <- function(ms3_lib) {
  ms2_lib <- ms3_lib %>%
    dplyr::mutate(fragmentLabel = paste0("ms3-{", as.character(ref_ms2_mz), "} ", fragmentLabel)) %>%
    dplyr::mutate(ref_ms2_mz = ref_ms3_mz) %>%
    dplyr::select(-ref_ms3_mz)

  ms2_lib
}

#' 13C MS2 lipid library
#'
#' Return a copy of library with a single 12C replaced for 13C in each compound.
#' All relevant columns are adjusted accordingly.
#'
#' @param ms2_lib
#'    msp lipid library dataframe imported via mzkitcpp::import_msp_lipids_library()
#'
#' @export
to_13C_lib <- function(ms2_lib) {
  ms2_13C_lib <- ms2_lib %>%
    dplyr::mutate(ref_ms2_mz = ifelse(ref_ms1_mz == ref_ms2_mz, ref_ms2_mz + 1.00335483521, ref_ms2_mz)) %>%
    dplyr::mutate(ref_ms1_mz = ref_ms1_mz + 1.00335483521) %>%
    dplyr::mutate(compoundName = paste0(compoundName, "_13C")) %>%
    dplyr::mutate(compositionSummary = paste0(compositionSummary, "_13C")) %>%
    dplyr::mutate(chainLengthSummary = paste0(chainLengthSummary, "_13C")) %>%
    dplyr::mutate(compoundMonoisotopicMass = compoundMonoisotopicMass + 1.00335483521)
  ms2_13C_lib
}

#' Chain Length Summary Library
#'
#' Converts a standard imported lipids library to one with a maximum of one
#' compound name per chain length summary.
#' Fragment labels related to sn chains will correspond appropriately with
#' ms2 m/z values.
#'
#' @param ms2_lib
#'     msp lipid library dataframe (can be generated by mzkitcpp::import_msp_lipids_library()).
#'
#' @export
to_one_per_chainLengthSummary <- function(ms2_lib) {
  col_names <- colnames(ms2_lib)

  # TODO: Why was this ever added here?
  # if ("ms2_intensity" %in% col_names) {
  #   ms2_lib <- ms2_lib %>% dplyr::select(-ms2_intensity)
  # }

  if ("prec_mzs" %in% col_names && "ms3_mz_str" %in% colnames(ms2_lib)) {
    # indicates an ms3 lib. multiple ref_ms2_mz values are possible, use ref_ms3_mz instead.

    ms2_lib_one_per_chainLengthSummary <- ms2_lib %>%
      dplyr::group_by(lipidClass, chainLengthSummary, adductName, prec_mzs, ms3_mz_str) %>%
      dplyr::slice(1, .preserve = TRUE) %>%
      dplyr::ungroup()
  } else {
    ms2_lib_one_per_chainLengthSummary <- ms2_lib %>%
      dplyr::group_by(lipidClass, chainLengthSummary, adductName, ref_ms2_mz) %>%
      dplyr::slice(1, .preserve = TRUE) %>%
      dplyr::ungroup()
  }

  ms2_lib_one_per_chainLengthSummary
}

#' Add Direct Infusion Search Results
#'
#' @description
#' Creates an mzrollDB file if it does not already exist. (calls create_mzrolldb)
#' Write the search results into the mzrollDB file as a new table of peak groups.
#' Adjust the Compounds table with all summarized Compounds.
#'
#' @param mzroll_db_path
#'      Absolute file path of mzroll_db_file.
#'      If the file does not yet exist, it will be created
#'
#' @param samples
#'      list of all samples analyzed in the experiment.
#'
#' @param ms2_ranges
#'      ms2_ranges used to generate di_search_results.
#'      Needed to properly determine composition of summarized compounds.
#'
#' @param library_name
#'      Name of library used to carry out search (msp file).
#'      This file should be imported into maven prior to opening mzrollDB file.
#'
#' @param search_lib_sliced
#'      Search library used to generate di_search_results.
#'      Needed to properly determine composition of summarized compounds.
#'
#' @param search_params
#'      list of parameter values used in search.
#'      If a parameter is not included in the list, use the default value.
#'      Empty list for default values.
#'
#' @param adducts_file
#'      adducts_file used to generate di_search_results.
#'      Needed to properly determine composition of summarized compounds.
#'
#' @param di_search_results
#'      search results from DIMS search.
#'
#' @param di_quant_ions
#'      hierarchical quant ions from DIMS search.
#'      A modification of the DIMS search adduct table, containing
#'      hierarchical ms1 intensity, hierarchical ms2 intensity, diagnostic ms2 intensity,
#'      nearest scan normalized ms1 intensity.
#'
#' @param set_name
#'      vector of designations to apply to each sample.
#'      if NULL or invalid, all samples will be in set "A".
#'
#' @param color_table
#'      tibble of pre-specified colors for samples.
#'      requires a tibble with numeric columns "red", "green", and "blue" and character column "sample_name"
#'      If the color_table has the sample_name, sample will receive that color. Otherwise, fall back to default algorithm.
#'
#' @param ui_options list of encoded UI options interpreted by MAVEN
#' @param verbose Print detailed messages/output if set to TRUE. default is TRUE.
#'
#' @export
add_direct_infusion_search_results <- function(mzroll_db_path,
                                               samples,
                                               ms2_ranges,
                                               library_name,
                                               search_lib_sliced,
                                               search_params,
                                               adducts_file,
                                               di_search_results,
                                               di_quant_ions,
                                               set_name = NULL,
                                               color_table = NULL,
                                               ui_options = NULL,
                                               verbose = TRUE) {
  mzroll_db_con <- open_mzrolldb(mzroll_db_path)

  # save search params
  search_name <- mzrolldb_next_search_name(mzroll_db_con, "Direct Infusion Analysis")
  search_params_tbl <- mzkitcpp::DI_encoded_search_params(search_params)

  DBI::dbAppendTable(mzroll_db_con, "search_params", tibble::tibble("searchTableName" = search_name, "parameters" = search_params_tbl))

  # ui options
  if (!is.null(ui_options)) {
    DBI::dbAppendTable(mzroll_db_con, "ui", ui_options)
  }

  if (verbose) {
    cat(paste0("Search results saved to mzrollDB as \"", search_name, "\".\n"))
  }

  # save summarized compounds
  compound_table <- create_compound_table(di_search_results, search_lib_sliced, ms2_ranges, adducts_file)

  if (nrow(compound_table) > 0) {
    DBI::dbAppendTable(mzroll_db_con, "compounds", compound_table)
    if (verbose) {
      cat(paste0("Saved ", nrow(compound_table), " summarized compounds to mzrollDB.\n"))
    }
  }

  # add samples to possible existing samples information, retrieve all samples information as data frame
  samples_tbl <- get_samples_table(mzroll_db_con, samples, set_name, color_table)

  # save peakgroups + peaks
  add_DIMS_peakgroups_and_peaks(
    mzroll_db_con,
    di_search_results,
    di_quant_ions,
    ms2_ranges,
    samples_tbl,
    library_name,
    search_name,
    verbose
  )

  DBI::dbDisconnect(mzroll_db_con)
}

#' Add Targeted MS3 Search Results
#'
#' @description
#' Creates an mzrollDB file if it does not already exist. (calls create_mzrolldb)
#' Write the search results into the mzrollDB file as a new table of peak groups.
#' Adjust the Compounds table with all summarized Compounds.
#'
#' @param mzroll_db_path
#'      Absolute file path of mzroll_db_file.
#'      If the file does not yet exist, it will be created
#'
#' @param samples
#'      list of all samples analyzed in the experiment.
#'
#' @param ms3_search_results
#'      Results of targeted ms3 search
#'
#' @param library_name
#'      Name of library used to carry out search (msp file).
#'      This file should be imported into maven prior to opening mzrollDB file.
#'
#' @param search_params
#'      list of parameter values used in search.
#'      If a parameter is not included in the list, use the default value.
#'      Empty list for default values.
#'
#' @param set_name
#'      vector of designations to apply to each sample.
#'      if NULL or invalid, all samples will be in set "A".
#'
#' @param color_table
#'      tibble of pre-specified colors for samples.
#'      requires a tibble with numeric columns "red", "green", and "blue" and character column "sample_name"
#'      If the color_table has the sample_name, sample will receive that color. Otherwise, fall back to default algorithm.
#'
#' @param verbose
#'      Print detailed messages/output if set to TRUE. default is TRUE.
#'
#' @export
add_targeted_ms3_search_results <- function(mzroll_db_path,
                                            samples,
                                            ms3_search_results,
                                            library_name,
                                            search_params,
                                            set_name = NULL,
                                            color_table = NULL,
                                            verbose = TRUE) {
  mzroll_db_con <- open_mzrolldb(mzroll_db_path)

  # save search params
  search_name <- mzrolldb_next_search_name(mzroll_db_con, "Targeted MS3 Search")
  search_params_tbl <- mzkitcpp::DI_encoded_search_params(search_params)

  DBI::dbAppendTable(mzroll_db_con, "search_params", tibble::tibble("searchTableName" = search_name, "parameters" = search_params_tbl))

  if (verbose) {
    cat(paste0("Search results saved to mzrollDB as \"", search_name, "\".\n"))
  }

  # add samples to possible existing samples information, retrieve all samples information as data frame
  samples_tbl <- get_samples_table(mzroll_db_con, samples, set_name, color_table)

  # save peakgroups + peaks
  add_MS3_peakgroups_and_peaks(
    mzroll_db_con,
    ms3_search_results,
    samples_tbl,
    library_name,
    search_name,
    verbose
  )

  DBI::dbDisconnect(mzroll_db_con)
}

#' Add MS3 Search Results to mzrollDB database
#'
#' @description
#' Reorganize search results data frame into peakgroups and peaks table
#' amenable for saving into mzrollDB file.
#'
#' @param mzroll_db_con
#'       connection to mzrollDB database file.
#'
#' @param ms3_search_results
#'      Results of targeted ms3 search
#'
#' @param samples_tbl
#'      complete samples table from mzrollDB, as a data frame
#'
#' @param library_name
#'       name of msp file associated with the library.
#'
#' @param search_name
#'       should be computed from mzrolldb_next_search_name() function
#'
#' @param verbose
#'       if true, display information about mapping of quant values to peak table fields
add_MS3_peakgroups_and_peaks <- function(mzroll_db_con, ms3_search_results, samples_tbl, library_name, search_name, verbose) {
  # remove suffix, absolute path, if provided
  library_name <- gsub(".msp$", "", basename(library_name))

  # determine starting peakId and groupId values
  first_peak_id <- DBI::dbGetQuery(mzroll_db_con, "SELECT MAX(peakId) FROM peaks")$`MAX(peakId)`[[1]]
  first_group_id <- DBI::dbGetQuery(mzroll_db_con, "SELECT MAX(groupId) from peakgroups")$`MAX(groupId)`[[1]]

  first_peak_id <- ifelse(is.na(first_peak_id), 1, (first_peak_id + 1))
  first_group_id <- ifelse(is.na(first_group_id), 1, (first_group_id + 1))

  if (!"label" %in% colnames(ms3_search_results)) {
    ms3_search_results["label"] <- rep("", nrow(ms3_search_results))
  }

  # remove fragment-specific information
  ms3_search_results_no_frags <- ms3_search_results %>%
    dplyr::inner_join(samples_tbl, by = c("sample" = "name")) %>%
    dplyr::select(
      sampleId, adductName, compoundName, label,
      # peakgroup related

      ref_ms1_mz, ref_ms2_mz,
      # peaks mz related

      num_matches, num_ms3_mz_matches, ms1_intensity, ms3_intensity_sum, ms3_intensity_sum_norm
      # peaks quantification related
    ) %>%
    unique() %>%
    dplyr::arrange(compoundName, adductName, ref_ms1_mz, ref_ms2_mz, sampleId) %>%
    # Issue 1910: avoid possible rounding issues caused by previous mzkitcpp calls
    dplyr::mutate(ref_ms1_mz = round(ref_ms2_mz, digits = 4), ref_ms2_mz = round(ref_ms2_mz, digits = 4))

  num_compounds <- ms3_search_results_no_frags %>%
    dplyr::select(compoundName, adductName) %>%
    unique() %>%
    nrow()

  num_targets <- ms3_search_results_no_frags %>%
    dplyr::select(compoundName, adductName, ref_ms1_mz, ref_ms2_mz) %>%
    unique() %>%
    nrow()

  num_peakgroups <- num_compounds + num_targets

  # every row in the table counts represents a peak for a target peak group.
  # every sample that has data for a compound rerpresents a peak for a compound peak group.
  num_peaks_compound_peakgroups <- ms3_search_results_no_frags %>%
    dplyr::select(compoundName, adductName, sampleId) %>%
    unique() %>%
    nrow()

  num_peaks <- num_peaks_compound_peakgroups + nrow(ms3_search_results_no_frags) # num_peaks_target_peakgroups

  # START TESTS

  # tg_section <- ms3_search_results_no_frags %>%
  #   dplyr::filter(compoundName %in% c("TG(18:0/18:0/18:2)", "TG(18:0/18:1/18:1)"))

  # subset_peaks_test <- ms3_search_results_no_frags %>%
  #   dplyr::filter(compoundName %in% c("TG(16:0/16:1/20:3)", "TG(18:0/18:1/18:1)", "TG(16:0/18:1/20:2)", "TG(16:0/18:1/22:5)"))

  # END TESTS

  peakgroups_and_peaks <- mzkitcpp::DI_ms3_peakgroups_and_peaks(
    ms3_search_results_no_frags, # subset_peaks_test, #ms3_search_results_no_frags,
    first_peak_id,
    first_group_id,
    num_peakgroups,
    num_peaks,
    search_name,
    library_name,
    verbose,
    F
  ) # debug

  # START VALIDATION

  # groups_and_scores <- peakgroups_and_peaks$peakgroups %>% dplyr::select(compoundName, tagString, ms2Score)
  # View(groups_and_scores)
  #
  # peaks_3_4_5 <- peakgroups_and_peaks$peaks %>%
  #   dplyr::filter(groupId %in% c(3,4,5)) %>%
  #   dplyr::select(groupId, sampleId, quality)
  #
  # TG_16_0_18_1_20_2 <- subset_peaks_test %>%
  #   dplyr::filter(compoundName == "TG(16:0/18:1/20:2)")

  # END VALIDATION

  DBI::dbAppendTable(mzroll_db_con, "peakgroups", peakgroups_and_peaks$peakgroups)
  DBI::dbAppendTable(mzroll_db_con, "peaks", peakgroups_and_peaks$peaks)

  if (verbose) {
    cat(paste0("Saved ", nrow(peakgroups_and_peaks$peakgroups), " peak groups to mzrollDB.\n"))
    cat(paste0("Saved ", nrow(peakgroups_and_peaks$peaks), " peaks to mzrollDB.\n"))
  }

  invisible(0)
}

#' Create table of summarized compound information
#'
#' @description
#' Generate data frame containing all necessary information for
#' summarized compounds.  Output format is ready to be written to an mzrollDB file.
#'
#' @param search_results
#'      search results from DIMS search.
#'
#' @param search_lib_sliced
#'      library searched to generate di_search_results.
#'
#' @param ms2_ranges
#'      ms2_ranges used to generate di_search_results.
#'
#' @param adducts_file
#'      adducts_file (absolute path) used to generate di_search_results.
#'
create_compound_table <- function(di_search_results, search_lib_sliced, ms2_ranges, adducts_file) {
  summarized_compounds <- di_search_results %>%
    dplyr::filter(grepl("^\\{", compoundId)) %>%
    dplyr::select(precursor_range_id, lipidClass, compositionSummary, chainLengthSummary, compoundName, compoundId, molecularFormula, compoundMonoisotopicMass, adductName, ref_ms1_mz) %>%
    unique()

  compound_table <- mzkitcpp::DI_summarized_compounds(summarized_compounds, search_lib_sliced, ms2_ranges, adducts_file)

  compound_table
}

#' Create Samples table
#'
#' @description
#' Generate samples table containing sample names and filenames.
#'
#' @param mzroll_db_con
#'       connection to mzrollDB database file.
#'
#' @param samples
#'       list of full absolute paths of samples that are not already in the mzrollDB
#'
#' @param set_name
#'      vector of designations to apply to each sample.
#'      if NULL or invalid, all samples will be in set "A".
#'
#' @param color_table
#'      tibble of pre-specified colors.
#'      require a tibble with numeric columns "red", "green", and "blue" and character column "sample_name"
#'      If the color_table has the sample_name, sample will receive that color
#'
#' @return
#' table of all samples in the mzrollDB file, including any samples already in the file not in
#' the input samples vector.
#'
get_samples_table <- function(mzroll_db_con, samples, set_name, color_table) {
  # retrieve existing samples info
  existing_samples <- DBI::dbGetQuery(mzroll_db_con, "SELECT * FROM samples ORDER BY sampleId")

  sample_id <- suppressWarnings(max(existing_samples$sampleId))
  if (sample_id == -Inf) {
    sample_id <- -1
  }

  updated_samples_tbl <- existing_samples

  if (is.null(set_name) || !is.character(set_name) || length(set_name) != length(samples)) {
    set_name <- rep("A", length(samples))
  }

  for (x in 1:length(samples)) {
    name <- basename(samples[x])

    if (!(name %in% existing_samples$name)) {
      color_red <- x / length(samples)
      color_green <- 1 - x / length(samples)
      color_blue <- 0.5 + 0.5 * (x / length(samples))

      if (!is.null(color_table)) {
        color_table_sample <- color_table %>% dplyr::filter(sample_name == name)

        if (nrow(color_table_sample) == 1) {
          color_red <- color_table_sample$red[1]
          color_green <- color_table_sample$green[1]
          color_blue <- color_table_sample$blue[1]
        }
      }

      sample_id <- sample_id + 1

      next_row <- tibble::tibble(
        sampleId = as.integer(sample_id),
        name = basename(samples[x]),
        filename = samples[x],
        setName = set_name[x],
        sampleOrder = sample_id,
        isSelected = 1,
        color_red = color_red,
        color_green = color_green,
        color_blue = color_blue,
        color_alpha = 1,
        norml_const = 1,
        transform_a0 = 0,
        transform_a1 = 0,
        transform_a2 = 0,
        transform_a4 = 0,
        transform_a5 = 0
      )

      updated_samples_tbl <- rbind(updated_samples_tbl, next_row)
    }
  }

  # replace old table with new table
  DBI::dbWriteTable(mzroll_db_con, "samples", updated_samples_tbl, overwrite = TRUE)

  updated_samples_tbl
}

#' Create Peak Groups and peaks tables from data
#'
#' @description
#' Reorganize search results data frame into peakgroups and peaks table
#' amenable for saving into mzrollDB file.
#'
#' @param mzroll_db_con
#'       connection to mzrollDB database file.
#'
#' @param di_search_results
#'      search results from DIMS search.
#'
#' @param di_quant_ions
#'      hierarchical quant ions from DIMS search.
#'      A modification of the DIMS search adduct table, containing
#'      hierarchical ms1 intensity, hierarchical ms2 intensity, diagnostic ms2 intensity,
#'      nearest scan normalized ms1 intensity.
#'
#' @param ms2_ranges
#'      ms2_ranges used to generate di_search_results.
#'
#' @param samples_tbl
#'      complete samples table from mzrollDB, as a data frame
#'
#' @param library_name
#'       name of msp file associated with the library.
#'
#' @param search_name
#'       should be computed from mzrolldb_next_search_name() function
#'
#' @param verbose
#'       if true, display information about mapping of quant values to peak table fields
add_DIMS_peakgroups_and_peaks <- function(
  mzroll_db_con,
  di_search_results,
  di_quant_ions,
  ms2_ranges,
  samples_tbl,
  library_name,
  search_name,
  verbose
) {
  # remove suffix, absolute path, if provided
  library_name <- gsub(".msp$", "", basename(library_name))

  # determine starting peakId and groupId values
  first_peak_id <- DBI::dbGetQuery(mzroll_db_con, "SELECT MAX(peakId) FROM peaks")$`MAX(peakId)`[[1]]
  first_group_id <- DBI::dbGetQuery(mzroll_db_con, "SELECT MAX(groupId) from peakgroups")$`MAX(groupId)`[[1]]

  first_peak_id <- ifelse(is.na(first_peak_id), 1, (first_peak_id + 1))
  first_group_id <- ifelse(is.na(first_group_id), 1, (first_group_id + 1))

  # Issue 507: Add possibility of compounds without any ms2 ranges
  ms2_ranges_adj <- rbind(ms2_ranges, tibble::tibble(
    precursor_range_id = c(-1), # DirectInfusionSearchSet::getNoMs2ScansMapKey()
    prec_min_mz = c(0),
    prec_max_mz = c(99999999),
    scan_min_mz = c(0),
    scan_max_mz = c(99999999)
  ))


  if (!"label" %in% colnames(di_search_results)) {
    di_search_results["label"] <- rep("", nrow(di_search_results))
  }

  # remove fragment-specific information
  di_search_results_no_frags <- di_search_results %>%
    dplyr::select(
      sample, precursor_range_id, adductName, compoundId, compoundName, chainLengthSummary, label,
      # for peakgroups (precursor_range_id == metaGroupId), chainLengthSummary provides clue if compound is summarized or not

      ref_ms1_mz,
      # peaks mz related

      num_matches,
      # peaks ID related

      ms1_scan_intensity,
      diagnostic_partition_fraction, acyl_partition_fraction, acyl_partition_fraction_SAF
      # peaks quantification related
    ) %>%
    unique()

  di_search_results_no_frags_w_extra <- di_search_results_no_frags %>%
    dplyr::inner_join(samples_tbl, by = c("sample" = "name")) %>%
    dplyr::inner_join(ms2_ranges_adj, by = c("precursor_range_id")) %>%
    dplyr::inner_join(di_quant_ions, by = c("sample", "compoundName", "adductName")) %>%
    dplyr::select(
      sampleId, precursor_range_id, adductName, compoundId, compoundName, chainLengthSummary, label,
      # for peakgroups (precursor_range_id == metaGroupId), chainLengthSummary provides clue if compound is summarized or not

      prec_min_mz, prec_max_mz, ref_ms1_mz,
      # peaks mz related

      num_matches,
      # peaks ID related

      ms1_scan_intensity,
      diagnostic_partition_fraction, acyl_partition_fraction, acyl_partition_fraction_SAF,
      # peaks quantification related from search table

      ms1_intensity_is_nearest_scan_normalized, diagnostic_ms2_intensity, ms1_intensity, ms2_intensity
      # peaks quantification related from quant ions table (may be centered/otherwise adjusted)
    ) %>%
    dplyr::arrange(precursor_range_id, adductName, compoundId)

  # START test code

  # di_search_results_last_row_new_pg <- di_search_results_no_frags
  # di_search_results_last_row_old_pg <- di_search_results_no_frags[1:(nrow(di_search_results_no_frags)-2),]
  #
  # num_peakgroups <- di_search_results_last_row_new_pg$compoundId %>% unique() %>% length()
  # peakgroups_and_peaks <- mzkitcpp::DI_peakgroups_and_peaks(di_search_results_last_row_new_pg, first_peak_id, first_group_id, num_peakgroups, search_table_name, library_name, TRUE, TRUE)
  #
  # num_peakgroups <- di_search_results_last_row_old_pg$compoundId %>% unique() %>% length()
  # peakgroups_and_peaks <- mzkitcpp::DI_peakgroups_and_peaks(di_search_results_last_row_old_pg, first_peak_id, first_group_id, num_peakgroups, search_table_name, library_name, TRUE, TRUE)
  #
  # END test code

  num_peakgroups <- di_search_results_no_frags_w_extra$compoundId %>%
    unique() %>%
    length()

  peakgroups_and_peaks <- mzkitcpp::DI_peakgroups_and_peaks(
    di_search_results_no_frags_w_extra,
    first_peak_id,
    first_group_id,
    num_peakgroups,
    search_name,
    library_name,
    verbose,
    FALSE
  ) # debug

  DBI::dbAppendTable(mzroll_db_con, "peakgroups", peakgroups_and_peaks$peakgroups)
  DBI::dbAppendTable(mzroll_db_con, "peaks", peakgroups_and_peaks$peaks)

  if (verbose) {
    cat(paste0("Saved ", nrow(peakgroups_and_peaks$peakgroups), " peak groups to mzrollDB.\n"))
    cat(paste0("Saved ", nrow(peakgroups_and_peaks$peaks), " peaks to mzrollDB.\n"))
  }

  invisible(0)
}

#' DIMS encoded quant type
#'
#' @description
#' As quant methods change, this function keeps things up to date
#'
#' @export
DIMS_encoded_quant_type <- function() {
  encoded_quantType <- "{AreaTop=ms1_scan_intensity;Area=normalized_ms1_intensity;Height=hierarchical_ms1_intensity;Retention Time=acyl_partitioned_intensity;Quality=diagnostic_ms2_intensity;Area Uncorrected=acyl_partition_fraction;Area Fractional=acyl_partition_fraction_SAF;S/N Ratio=hierarchical_ms2_intensity;}"
}

#' Calculate next table name from list of existing tables
#'
#' Add searches to table based on base table name and serial number.
#'
#' The first search of a type receives no serial number.
mzrolldb_next_search_name <- function(mzroll_db_con, search_name_base) {
  previous_searches <- DBI::dbGetQuery(mzroll_db_con, "SELECT searchTableName FROM search_params") %>%
    dplyr::filter(grepl(paste0("^", search_name_base), searchTableName)) %>%
    dplyr::mutate(analysis_num = as.integer(stringr::str_extract(searchTableName, "[0-9]+$")))

  last_analysis_num <- suppressWarnings(max(previous_searches$analysis_num, na.rm = TRUE))

  if (last_analysis_num == -Inf && nrow(previous_searches) == 1) {
    last_analysis_num <- 1
  }

  search_name <- ifelse(last_analysis_num == -Inf, search_name_base, paste0(search_name_base, " ", as.character(last_analysis_num + 1)))

  search_name
}

#' Open mzrolldb file
#'
#' @description
#' Opens an existing mzrollDB file, or creates one, using the provided file path.
#'
#' @param mzroll_db_path
#'      full file path of mzrollDB file (if it does not already exist, will be created.)
#'
#' @export
open_mzrolldb <- function(mzroll_db_path) {
  if (!grepl(".mzrollDB$", mzroll_db_path)) {
    stop(paste0("database file \"", mzroll_db_path, "\" is not an mzrollDB file."))
  }

  if (!file.exists(mzroll_db_path)) {
    create_mzrolldb(mzroll_db_path)
  }

  mzroll_db_con <- DBI::dbConnect(RSQLite::SQLite(), mzroll_db_path)

  mzroll_db_con
}
#' Create mzrolldb file
#'
#' @description
#' Creates an mzrolldb file, with all schema requirements necessary for
#' direct infusion experiments.
#'
#' @export
create_mzrolldb <- function(mzroll_db_path) {
  # silently overwrite any existing file
  if (file.exists(mzroll_db_path)) {
    file.remove(mzroll_db_path)
  }

  mzroll_db_con <- DBI::dbConnect(RSQLite::SQLite(), mzroll_db_path)

  DBI::dbExecute(
    mzroll_db_con,
    "CREATE TABLE samples(sampleId integer primary key AUTOINCREMENT,
                 name varchar(254),
                 filename varchar(254),
                 setName varchar(254),
                 sampleOrder int,
                 isSelected int,
                 color_red real,
                 color_green real,
                 color_blue real,
                 color_alpha real,
                 norml_const real,
                 transform_a0 real,
                 transform_a1 real,
                 transform_a2 real,
                 transform_a4 real,
                 transform_a5 real);"
  )

  DBI::dbExecute(mzroll_db_con, "CREATE TABLE rt_update_key(sampleId int NOT NULL, rt real NOT NULL, rt_update real NOT NULL);")

  DBI::dbExecute(mzroll_db_con, "CREATE TABLE peakgroups (groupId integer primary key AUTOINCREMENT,
                 parentGroupId integer,
                 tagString varchar(254),
                 metaGroupId integer,
                 expectedRtDiff real,
                 groupRank int,
                 label varchar(10),
                 type integer,
                 srmId varchar(254),
                 ms2EventCount int,
                 ms2Score real,
                 adductName varchar(32),
                 compoundId varchar(254),
                 compoundName varchar(254),
                 compoundDB varchar(254),
                 searchTableName varchar(254),
                 displayName varchar(254));")

  DBI::dbExecute(mzroll_db_con, "CREATE TABLE peaks(peakId integer primary key AUTOINCREMENT,
                 groupId int,
                 sampleId int,
                 pos int,
                 minpos int,
                 maxpos int,
                 rt real,
                 rtmin real,
                 rtmax real,
                 mzmin real,
                 mzmax real,
                 scan int,
                 minscan int,
                 maxscan int,
                 peakArea real,
                 peakAreaCorrected real,
                 peakAreaTop real,
                 peakAreaFractional real,
                 peakRank real,
                 peakIntensity real,
                 peakBaseLineLevel real,
                 peakMz real,
                 medianMz real,
                 baseMz real,
                 quality real,		width int,
                 gaussFitSigma real,
                 gaussFitR2 real,
                 noNoiseObs int,
                 noNoiseFraction real,
                 symmetry real,
                 signalBaselineRatio real,
                 groupOverlap real,
                 groupOverlapFrac real,
                 localMaxFlag real,
                 fromBlankSample int,
                 label int);")

  DBI::dbExecute(mzroll_db_con, "CREATE TABLE search_params(searchTableName TEXT,parameters TEXT);")

  DBI::dbExecute(mzroll_db_con, "CREATE TABLE compounds(cid integer primary key AUTOINCREMENT,
                 dbName varchar(255),
                 compoundId varchar(255),
                 name varchar(255),
                 adductString varchar(255),
                 formula varchar(255),
                 smileString  varchar(255),
                 srmId  varchar(255),
                 mass float,
                 charge  int,
                 expectedRt float,
                 precursorMz float,
                 productMz   float,
                 collisionEnergy float,
                 logP float,
                 virtualFragmentation int,
                 ionizationMode int,
                 category varchar(255),
                 fragment_mzs text,
                 fragment_intensity text,
                 fragment_labels text,
                 UNIQUE(dbName, compoundId) ON CONFLICT IGNORE);")

  DBI::dbExecute(mzroll_db_con, "CREATE INDEX compound_db_idx on compounds(dbName);")

  DBI::dbExecute(mzroll_db_con, "CREATE TABLE matches(groupId INT NOT NULL,
                 ionId INT NOT NULL,
                 compoundName TEXT,
                 adductName TEXT,
                 summarizationLevel INT,
                 originalCompoundName TEXT,
                 score REAL,
                 is_match INT);")

  # Issue 646: Introduce UI options table
  DBI::dbExecute(mzroll_db_con, "CREATE TABLE ui(key TEXT, value TEXT);")

  DBI::dbExecute(mzroll_db_con, "CREATE INDEX peak_group_ids on peaks(groupId);")

  DBI::dbDisconnect(mzroll_db_con)
}

#' Delete bad peak groups
#'
#' @description
#' Deletes all peak groups and peaks marked as "bad".
#' This is applied equally to all peak groups, even those that are bookmarked.
#'
#' @param mzroll_db_path
#'      full file path of mzrollDB file (if it does not already exist, exit in error)
#'
#' @param verbose
#'      Display progress, messages about results
#'
#' @export
delete_bad_peak_groups <- function(mzroll_db_path, verbose = FALSE) {
  if (!file.exists(mzroll_db_path)) {
    stop(paste0("mzroll db path '", mzroll_db_path, "' does not exist."))
  }

  mzroll_db_con <- DBI::dbConnect(RSQLite::SQLite(), mzroll_db_path)

  delete_peakgroups_query <- "SELECT groupId FROM peakgroups WHERE peakgroups.label like '%b%';"
  if (verbose) {
    cat(paste0("Deleting peak groups with query: ", delete_peakgroups_query, "\n"))
  }
  bad_peak_groups <- DBI::dbGetQuery(mzroll_db_con, "SELECT groupId FROM peakgroups WHERE peakgroups.label like '%b%';")

  if (verbose) {
    cat(paste0("Found ", nrow(bad_peak_groups), " peak groups to delete.\n"))
  }

  DBI::dbExecute(mzroll_db_con, "DELETE FROM peakgroups WHERE peakgroups.label like '%b%';")

  if (nrow(bad_peak_groups) > 0) {
    sql_query <- "DELETE FROM peaks where peaks.groupId in ("
    for (i in 1:nrow(bad_peak_groups)) {
      if (i %% 100 == 0 || i == nrow(bad_peak_groups)) {
        if (i == nrow(bad_peak_groups)) {
          sql_query <- paste0(sql_query, ", ", as.character(bad_peak_groups$groupId[i]), ");")
        } else {
          sql_query <- paste0(sql_query, ");")
        }

        if (verbose) {
          cat(paste0("Deleting peaks with query: ", sql_query, "\n"))
        }
        DBI::dbExecute(mzroll_db_con, sql_query)

        # finished, if last ID handled
        if (i == nrow(bad_peak_groups)) {
          break
        }

        # restart, if last ID not handled
        sql_query <- "DELETE FROM peaks where peaks.groupId in ("
      } else if (i > 1) {
        sql_query <- paste0(sql_query, ", ")
      }

      sql_query <- paste0(sql_query, as.character(bad_peak_groups$groupId[i]))
    }
  }

  DBI::dbDisconnect(mzroll_db_con)

  invisible(0)
}

#' Delete bad peak groups
#'
#' @description
#' Deletes all peak groups and peaks marked as "bad".
#' This is applied equally to all peak groups, even those that are bookmarked.
#'
#' @param mzroll_db_path
#'      full file path of mzrollDB file (if it does not already exist, exit in error)
#'
#' @param di_search_results
#'      results of DI pipeline search associated with mzroll_db_path
#'
#' @param verbose
#'      Display progress, messages about results
#'
#' @export
filter_bad_peak_groups <- function(mzroll_db_path, di_search_results, verbose = FALSE) {
  if (!file.exists(mzroll_db_path)) {
    stop(paste0("mzroll db path '", mzroll_db_path, "' does not exist."))
  }

  mzroll_db_con <- DBI::dbConnect(RSQLite::SQLite(), mzroll_db_path)

  bad_peak_groups_query <- "SELECT compoundId FROM peakgroups WHERE peakgroups.label like '%b%';"

  bad_peak_groups <- DBI::dbGetQuery(mzroll_db_con, bad_peak_groups_query)

  DBI::dbDisconnect(mzroll_db_con)

  if (verbose) {
    cat(paste0("Retrieved ", nrow(bad_peak_groups), " bad peak groups with query: ", bad_peak_groups_query, "\n"))
    cat(paste0(nrow(bad_peak_groups), " peak groups will be removed:\n"))
    cat(paste0(bad_peak_groups$compoundId, collapse = "\n"))
  }

  filtered_di_search_results <- di_search_results %>% dplyr::filter(!(compoundId %in% bad_peak_groups$compoundId))

  filtered_di_search_results
}

#' MAVEN DI analysis default parameters
#'
#' @description
#' Returns default parameters defined in DirectInfusionSearchParameters
#' class, in list() format that mzkitcpp::DI_pipeline() can understand
#'
#' @param verbose
#'      Display descriptions/notes about certain arguments,
#'      list of all arguments
#'
#' @export
maven_di_parameters <- function(verbose = FALSE) {
  if (verbose) {
    cat(paste0("NOTES:\n"))
    cat(paste0("\"scanFilterPrecursorPurityPpm\" is an unused parameter.\n"))
    cat(paste0("\"scanFilterMs1MinRt\": value of -1 to ignore this filter.\n"))
    cat(paste0("\"scanFilterMs1MaxRt\": value of -1 to ignore this filter.\n"))
    cat(paste0("\"scanFilterMs2MinRt\": value of -1 to ignore this filter.\n"))
    cat(paste0("\"scanFilterMs2MaxRt\": value of -1 to ignore this filter.\n"))
    cat(paste0("\"scanFilterMs3MinRt\": value of -1 to ignore this filter.\n"))
    cat(paste0("\"scanFilterMs3MaxRt\": value of -1 to ignore this filter.\n"))
    cat(paste0(
      "\"consensusIntensityAgglomerationType\" takes values of MEAN or MEDIAN.\n",
      "\tUsed everywhere a vector of quant measurements needs to be summarized into a single value.\n"
    ))
    cat(paste0("\"consensusMinNumMs2Scans\": fragment must be found in at least this many MS2 scans to be retained.\n"))
    cat(paste0("\"consensusMinFractionMs2Scans\": fraction between 0 and 1 --> 0.5 = fragment found in 50% of MS2 scans.\n"))
    cat(paste0("\"ms3MinNumMs3MzMatches\": Minimum number of reference MS3 m/zs found in observed MS3 scans, regardless of precursor m/zs.\n"))
    cat(paste0("\"spectralCompositionAlgorithm\": ALL_CANDIDATES, AUTO_SUMMARIZED_IDENTICAL_FRAGMENTS, and AUTO_SUMMARIZED_ACYL_CHAINS_SUM_COMPOSITION\n"))
    cat(paste0("\"ms1PartitionIntensityByFragments\" is an unused parameter.\n"))
  }

  params <- list(
    # MAVEN version information
    "searchVersion" = "UNKNOWN",

    # scan filter params (all ms levels)
    "scanFilterMinFracIntensity" = 0,
    "scanFilterMinSNRatio" = 0,
    "scanFilterMaxNumberOfFragments" = -1,
    "scanFilterBaseLinePercentile" = 0,
    "scanFilterIsRetainFragmentsAbovePrecursorMz" = TRUE,
    "scanFilterPrecursorPurityPpm" = 0, # UNUSED PARAMETER
    "scanFilterMinIntensity" = 0,

    # scan filter for MS1 scans
    "scanFilterMs1MinRt" = -1, # -1 to ignore this filter
    "scanFilterMs1MaxRt" = -1, # -1 to ignore this filter

    # scan filter for MS2 scans
    "scanFilterMs2MinRt" = -1, # -1 to ignore this filter
    "scanFilterMs2MaxRt" = -1, # -1 to ignore this filter

    # scan filter for MS3 scans
    "scanFilterMs3MinRt" = -1, # -1 to ignore this filter
    "scanFilterMs3MaxRt" = -1, # -1 to ignore this filter

    # consensus spectrum params (all ms levels)
    "consensusIsIntensityAvgByObserved" = TRUE,
    "consensusIsNormalizeTo10K" = FALSE,
    "consensusIntensityAgglomerationType" = "MEAN", # alternative: "MEDIAN"
    # this parameter is also used in computation of ms1_intensity_is_scan_normalized value

    # consensus spectrum formation of MS1 scans
    "consensusMs1PpmTolr" = 10,
    "consensusMinNumMs1Scans" = 0,
    "consensusMinFractionMs1Scans" = 0,

    # consensus spectrum formation of MS2 scans
    "consensusPpmTolr" = 10,
    "consensusMinNumMs2Scans" = 0, # fragment must be found in at least this many MS2 scans to be retained
    "consensusMinFractionMs2Scans" = 0, # fraction between 0 and 1 --> 0.5 = fragment found in 50% of MS2 scans
    "consensusIsRetainOriginalScanIntensities" = FALSE, # set to true for use with partition fractions

    # ms3 search params
    "ms3IsMs3Search" = FALSE,
    "ms3MinNumMatches" = 1,
    "ms3MinNumMs3MzMatches" = 1, # Minimum number of reference MS3 m/zs found in observed MS3 scans, regardless of precursor m/zs
    "ms3AnalysisMs1PrecursorPpmTolr" = 20,
    "ms3PrecursorPpmTolr" = 20,
    "ms3MatchTolrInDa" = 0.5,
    "ms3MinIntensity" = 0.0,
    "ms3IntensityType" = "MAX_INTENSITY",
    "ms3MinNumScans" = 0,
    "ms3MinFractionScans" = 0,

    # ms2 search params
    "ms2MinNumMatches" = 5,
    "ms2MinNumDiagnosticMatches" = 0,
    "ms2MinNumUniqueMatches" = 0,
    "ms2PpmTolr" = 20,
    "ms2MinIntensity" = 0,
    "ms2DiagnosticFragmentLabelTag" = "*",
    "ms2sn1FragmentLabelTag" = "@",
    "ms2sn2FragmentLabelTag" = "$",
    "ms2MinNumMatchesByLipidClassAndAdduct" = tibble::tibble("lipidClass" = character(0), "adductName" = character(0), "ms2MinNumMatches" = integer(0)),
    "ms2MinNumDiagnosticMatchesByLipidClassAndAdduct" = tibble::tibble("lipidClass" = character(0), "adductName" = character(0), "ms2MinNumDiagnosticMatches" = integer(0)),
    "ms2sn1MinNumMatches" = 0,
    "ms2sn2MinNumMatches" = 0,
    "ms2IsRequirePrecursorMatch" = FALSE,
    "ms2sn1MinNumMatchesByLipidClassAndAdduct" = tibble::tibble("lipidClass" = character(0), "adductName" = character(0), "ms2sn1MinNumMatches" = integer(0)),
    "ms2sn2MinNumMatchesByLipidClassAndAdduct" = tibble::tibble("lipidClass" = character(0), "adductName" = character(0), "ms2sn2MinNumMatches" = integer(0)),
    "ms2IsRequirePrecursorMatchByLipidClassAndAdduct" = tibble::tibble("lipidClass" = character(0), "adductName" = character(0), "ms2IsRequirePrecursorMatch" = logical(0)),

    # ms1 search params
    "ms1IsRequireAdductPrecursorMatch" = TRUE,
    "ms1IsFindPrecursorIon" = FALSE,
    "ms1IsMPlusOneValidPrecursor" = FALSE,
    "ms1PpmTolr" = 5,
    "ms1MinIntensity" = 0,
    "ms1ScanFilter" = "",
    "ms1IsRequireMonoisotopic" = TRUE,
    "ms1MMinusOnePeakMaxIntensityFraction" = 1,
    "ms1MinScanIntensity" = 0,

    # DIMS intensity options
    "ms1PartitionIntensityByFragments" = c("sn1", "sn2"), # Issue 451 UNUSED PARAMETER
    "isPreferSmallestScanMassWindow" = TRUE, # Issue 481
    "minNumScansNearestScanNormalizedIntensity" = 2, # Issue 536, Maven 325
    "minNumScansMs1ScanIntensity" = 2, # Issue 606/614, Maven 393
    "normClassMap" = tibble::tibble("lipidClass" = c("Alkyl_PC", "Alkyl_PE"), "normLipidClass" = c("Alkenyl_PC", "Alkenyl_PE")), # Issue 725, Maven 525

    # DIMS intensity partitioning options
    "partFragMinNumScans" = 0, # Issue 682, Maven 470
    "partFragMaxCV" = 0, # Issue 682, Maven 470
    "partFragMinIntensity" = 0, # Issue 682, Maven 470

    # spectral agglomeration params
    "isAgglomerateAcrossSamples" = FALSE,
    "spectralCompositionAlgorithm" = "ALL_CANDIDATES",
    # alternatives:
    #   "AUTO_SUMMARIZED_IDENTICAL_FRAGMENTS"
    #         compounds with identical matching fragments are summarized into a single compound.
    #
    #   "AUTO_SUMMARIZED_ACYL_CHAINS_SUM_COMPOSITION"
    #         compounds with identical matching fragments are summarized into a single compound.
    #         If the compounds can be named based on acyl chain composition or sum composition,
    #         this name will be preferred over a general name.

    "isReduceBySimpleParsimony" = FALSE
  )

  if (verbose) {
    param_names <- names(params)
    for (i in 1:length(params)) {
      cat(paste0(param_names[i], ": ", params[[i]], "\n"))
    }
  }

  return(params)
}

#' Summarized DIMS pipeline search results to simple MS1 summary
#'
#' @description
#' Returns summarized view of search results, with only a
#' subset of MS1-level information columns. All MS2-level
#' and sample metadata columns are excluded.
#'
#' @export
to_DI_simple_summary <- function(search_results) {
  ms1_level_search_results <- search_results %>%
    dplyr::select(
      sample, precursor_range_id, partitionGroupId, compositionSummaryId, compoundId,
      lipidClass, compositionSummary, compoundName, adductName, ref_ms1_mz,
      num_matches,
      ms1_scan_intensity, ms1_intensity_is_nearest_scan_normalized,
      ms1_partition_fragment_group_id, ms1_partition_fraction, ms1_partition_fraction_SAF
    ) %>%
    unique()
}

#' DIMS Pipeline Quant Results
#'
#' @description
#' Returns adduct_table reformatted as quant results.
#'
#' @param adduct_table
#'      input table
#'
#' @param is_auto_summarize
#'      For every \code{ref_ms1_mz}, if there are any compounds associated with that \code{ref_ms1_mz} where both
#'      the \code{acyl_partition_fraction} and \code{diagnostic_fragment_partition} cannot be computed
#'      without the SAF assumption, all compounds associated with that \code{ref_ms1_mz} are autosummarized to the
#'      compositionSummary level, if one is available.
#'
#' @param is_collapse_quant
#'      Return single summarized quant column, with another column for quant type.  Quant is determined
#'      based on a hierarchy of available computations.
#'
#' @format a data frame including four quant types, or \code{NA} if the quant type is inappropriate.
#' \describe{
#'    \item{\code{ms1_intensity}}{nearest scan IS normalized intensity of an unambiguous MS1 signal.}
#'    \item{\code{ms2_intensity}}{IS normalized intensity of most intense diagnostic MS2 fragment.}
#'    \item{\code{diagnostic_partitioned_intensity}}{ms1_intensity * diagnostic partitioned intensity, when diagnostic ions have unambiguous sources.}
#'    \item{\code{acyl_partitioned_intensity}}{ms1_intensity * acyl chain partitioned intensity, when all acyl chain fragments have unambiguous sources.}
#' }
#'
#' @export
to_quant_table <- function(
  adduct_table,
  is_auto_summarize,
  is_collapse_quant
) {
  quant_table <- adduct_table %>%
    dplyr::filter(is_identified) %>%
    dplyr::group_by(sample, ref_ms1_mz) %>%
    dplyr::mutate(num_ms1_mz = n()) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(is_unique_ms1 = num_ms1_mz == 1) %>%
    # Appropriate for MS1 partitioning criteria
    dplyr::mutate(is_unique_ms1_diagnostic = diagnostic_partition_fraction >= 0) %>%
    dplyr::mutate(is_unique_ms1_acyl_chains = acyl_partition_fraction >= 0) %>%
    # Appropriate for pure normalized MS2 quant
    dplyr::mutate(is_unique_ms2_diagnostic = diagnostic_fragment_sum_is_normalized >= 0) %>%
    dplyr::mutate(is_unique_ms2_acyl_chains = acyl_fragment_sum_is_normalized >= 0) %>%
    dplyr::mutate(diagnostic_partitioned_intensity = ifelse(is_unique_ms1_diagnostic & !is_unique_ms1, diagnostic_partition_fraction * ms1_intensity_is_nearest_scan_normalized, NA)) %>%
    dplyr::mutate(acyl_partitioned_intensity = ifelse(is_unique_ms1_acyl_chains & !is_unique_ms1, acyl_partition_fraction * ms1_intensity_is_nearest_scan_normalized, NA)) %>%
    dplyr::mutate(acyl_SAF_partitioned_intensity = ifelse(!is_unique_ms1 & !is_unique_ms1_acyl_chains, acyl_partition_fraction_SAF * ms1_intensity_is_nearest_scan_normalized, NA)) %>%
    dplyr::mutate(diagnostic_ms2_intensity = ifelse(is_unique_ms2_diagnostic, ms2_diagnostic_norm_intensity, NA)) %>%
    dplyr::mutate(ms1_intensity = ifelse(is_unique_ms1, ms1_intensity_is_nearest_scan_normalized, NA))

  quant_table_auto_summarized <- quant_table %>%
    dplyr::mutate(is_ambiguous_partitioning = (acyl_partition_fraction == -1 & diagnostic_partition_fraction == -1)) %>%
    dplyr::group_by(sample, ref_ms1_mz) %>%
    dplyr::mutate(is_auto_summarized = is_auto_summarize & any(is_ambiguous_partitioning)) %>%
    dplyr::mutate(is_cross_class_partitioning = length(unique(lipidClass)) != 1) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(compoundName = ifelse(is_auto_summarized & compositionSummary != "", compositionSummary, compoundName))

  if (is_collapse_quant) {
    quant_table_collapsed <- quant_table_auto_summarized %>%
      dplyr::mutate(hierarchical_ms1_intensity = case_when(
        is_auto_summarized | !is.na(ms1_intensity) ~ as.numeric(ms1_intensity),
        !is.na(acyl_partitioned_intensity) ~ as.numeric(acyl_partitioned_intensity),
        !is.na(acyl_SAF_partitioned_intensity) ~ as.numeric(acyl_SAF_partitioned_intensity),
        TRUE == TRUE ~ NaN
      )) %>%
      dplyr::mutate(hierarchical_ms2_intensity = case_when(
        !is.na(diagnostic_ms2_intensity) ~ as.numeric(diagnostic_ms2_intensity),
        !is.na(acyl_fragment_sum_is_normalized) ~ as.numeric(acyl_fragment_sum_is_normalized),
        !is.na(acyl_fragment_sum_SAF_is_normalized) ~ as.numeric(acyl_fragment_sum_SAF_is_normalized),
        TRUE == TRUE ~ NaN
      )) %>%
      dplyr::mutate(hierarchical_ms1_intensity = ifelse(is.nan(hierarchical_ms1_intensity), NA, hierarchical_ms1_intensity)) %>%
      dplyr::mutate(hierarchical_ms2_intensity = ifelse(is.nan(hierarchical_ms2_intensity), NA, hierarchical_ms2_intensity)) %>%
      dplyr::mutate(ms1_quant_type = case_when(
        is_auto_summarized | !is.na(ms1_intensity) ~ "ms1_intensity",
        !is.na(acyl_partitioned_intensity) & is_cross_class_partitioning == FALSE ~ "acyl_partitioned_intensity",
        !is.na(acyl_partitioned_intensity) & is_cross_class_partitioning == TRUE ~ "cross_class_acyl_partitioned_intensity",
        # !is.na(diagnostic_partitioned_intensity) & is_cross_class_partitioning==FALSE ~ "diagnostic_partitioned_intensity",
        # !is.na(diagnostic_partitioned_intensity) & is_cross_class_partitioning==TRUE ~ "cross_class_diagnostic_partitioned_intensity",
        !is.na(acyl_SAF_partitioned_intensity) & is_cross_class_partitioning == FALSE ~ "acyl_SAF_partitioned_intensity",
        !is.na(acyl_SAF_partitioned_intensity) & is_cross_class_partitioning == TRUE ~ "cross_class_acyl_SAF_partitioned_intensity",
        TRUE == TRUE ~ ""
      )) %>%
      dplyr::mutate(ms2_quant_type = case_when(
        !is.na(diagnostic_ms2_intensity) ~ "diagnostic_ms2_intensity",
        !is.na(acyl_fragment_sum_is_normalized) ~ "acyl_fragment_sum_is_normalized",
        !is.na(acyl_fragment_sum_SAF_is_normalized) ~ "acyl_fragment_sum_SAF_is_normalized",
        TRUE == TRUE ~ ""
      ))

    quant_table_output <- quant_table_collapsed %>%
      dplyr::select(sample, lipidClass, compositionSummary, compoundName, adductName, hierarchical_ms1_intensity, ms1_quant_type, hierarchical_ms2_intensity, ms2_quant_type) %>%
      dplyr::rename(ms1_intensity = hierarchical_ms1_intensity, ms2_intensity = hierarchical_ms2_intensity) %>%
      dplyr::arrange(sample, compositionSummary, compoundName, adductName)
  } else {
    quant_table_output <- quant_table_auto_summarized %>%
      dplyr::select(
        sample, lipidClass, compositionSummary, compoundName, adductName,
        ms1_intensity, diagnostic_partitioned_intensity, acyl_partitioned_intensity, acyl_SAF_partitioned_intensity,
        diagnostic_ms2_intensity, acyl_fragment_sum_is_normalized, acyl_fragment_sum_SAF_is_normalized
      ) %>%
      dplyr::arrange(sample, compositionSummary, compoundName, adductName)
  }

  quant_table_output
}

#' Expand Summarized Names
#'
#' @description
#' Decode encoded string vector containing summarized names, turning the vector of names
#' into a tibble of compoundName, adductName.
#'
#' @param summarized_names
#'      character vector containing summarized names, generated using AUTO_SUMMARIZED_IDENTICAL_FRAGMENTS
#'
#' @format a data frame of compoundName, adductName
#'
#' @export
expand_summarized_names <- function(summarized_names) {
  component_compounds_ids <- tibble::tibble(compoundName = character(0), adductName = character(0))

  for (i in 1:length(summarized_names)) {
    summarized_ids <- stringr::str_split(substr(summarized_names[i], 2, str_length(summarized_names[i]) - 1), ";")
    summarized_ids <- summarized_ids[[1]]
    for (j in 1:length(summarized_ids)) {
      summarized_id_bits <- stringr::str_split(summarized_ids[j], "\\|")
      summarized_id_bits <- summarized_id_bits[[1]]
      compound_name <- summarized_id_bits[1]
      adduct_name <- summarized_id_bits[2]

      component_compounds_ids <- rbind(component_compounds_ids, tibble::tibble(compoundName = compound_name, adductName = adduct_name))
    }
  }

  component_compounds_ids <- component_compounds_ids %>%
    unique() %>%
    arrange(compoundName, adductName)
}

#' DIMS Whitelist Search
#'
#' Wrapper to mzkitcpp::DI_pipeline() that handles the steps of whitelist-based searching
#' into a single function.
#'
#' @param samples_df
#'      Table of samples data
#'
#' @param ms2_ranges
#'      MS2 ranges, as computed by mzkitcpp::DI_ms2_ranges()
#'
#' @param IS_search_results
#'      results from previous mzkitcpp::DI_pipeline() search on IS
#'
#' @param IS_search_parameters
#'      Parameters used for identification of IS
#'
#' @param whitelist_search_parameters
#'      Parameters to be used in the initial whitelist search,
#'      results of which are used to filter the library for subsequent standard search
#'
#' @param regular_search_parameters
#'      Search parameters used for ordinary DIMS search,
#'      applied to the sample-specific library generated from the whitelist search.
#'
#' @param IS_sliced_lib
#'      Sliced library used in previous IS search results
#'
#' @param full_library_w_13C
#'      Complete lipids library as table, with all _13C compounds added.
#'
#' @param adducts_file
#'      File path of adducts file.  Necessary for mzkitcpp::DI_pipeline()
#'
#' @param whitelist_search_results_filter_fcn
#'      Additional filter function for search results from whitelist search.
#'      ignored if NULL (default value)
#'
#' @param debug
#'      Flag that will be passed onto mzkitcpp::DI_pipeline().
#'      If true, print debugging output.
#'
#' @export
DIMS_whitelist_search <- function(samples_df,
                                  ms2_ranges,
                                  IS_search_results,
                                  IS_search_parameters,
                                  whitelist_search_parameters,
                                  regular_search_parameters,
                                  IS_sliced_lib,
                                  full_library_w_13C,
                                  adducts_file,
                                  whitelist_search_results_filter_fcn = NULL,
                                  debug = FALSE) {
  lib_top_adducts <- dplyr::inner_join(full_library_w_13C, IS_search_results$IS_quant, by = c("lipidClass", "adductName")) %>%
    dplyr::filter(rank == 1) %>%
    dplyr::filter(!grepl("_13C$", compoundName))

  lib_top_adducts_sliced <- mzkitcpp::DI_slice_library(ms2_ranges, lib_top_adducts)

  # Most abundant form should retain this criterion in the larger search
  whitelist_search_results <- mzkitcpp::DI_pipeline(
    samples = samples_df$file,
    ms2_ranges = ms2_ranges,
    is_sliced_lib = IS_sliced_lib,
    is_search_params = IS_search_parameters,
    sliced_lib = lib_top_adducts_sliced,
    search_params = whitelist_search_parameters,
    adducts_file = adducts_file,
    debug = F
  )

  white_list_compounds <- NULL

  if (is.null(whitelist_search_results_filter_fcn)) {
    whitelist_compounds <- whitelist_search_results$search %>%
      dplyr::select(sample, compoundName) %>%
      unique()
  } else {
    whitelist_compounds <- do.call(whitelist_search_results_filter_fcn, list(whitelist_search_results = whitelist_search_results))
  }

  search_results <- NULL

  # searches use a more refined library
  for (i in 1:nrow(samples_df)) {
    sample_name <- samples_df$sample_name[i]
    sample_files <- c(samples_df$file[i])

    sample_whitelist_compounds <- whitelist_compounds %>%
      dplyr::filter(sample == sample_name)

    sample_library <- full_library_w_13C %>% dplyr::filter(compoundName %in% sample_whitelist_compounds$compoundName)
    sample_library_13C <- clamr::to_13C_lib(sample_library)
    sample_library_full <- rbind(sample_library, sample_library_13C)
    sample_library_full_sliced <- mzkitcpp::DI_slice_library(ms2_ranges, sample_library_full)

    single_sample_search_results <- mzkitcpp::DI_pipeline(
      samples = sample_files,
      ms2_ranges = ms2_ranges,
      is_sliced_lib = IS_sliced_lib,
      is_search_params = IS_search_parameters,
      sliced_lib = sample_library_full_sliced,
      search_params = regular_search_parameters,
      adducts_file = adducts_file,
      debug = F
    )

    if (i == 1) {
      search_results <- single_sample_search_results
    } else {
      search_results$search <- rbind(search_results$search, single_sample_search_results$search)
      search_results$adduct_table <- rbind(search_results$adduct_table, single_sample_search_results$adduct_table)
      search_results$IS_quant <- rbind(search_results$IS_quant, single_sample_search_results$IS_quant)
    }
  }

  search_results
}

#' DIMS read search params
#'
#' @description
#' read json file containing search params
#'
#' @param params_file full path of json file containing DIMS search params.
#'
#' @export
DIMS_read_search_params <- function(params_file) {
  params_reimported <- jsonlite::read_json(params_file)

  params_reformated <- list()
  params_names <- names(params_reimported)

  for (i in 1:length(params_reimported)) {
    ith_value <- params_reimported[[i]]

    # single parameter
    if (class(ith_value[[1]]) != "list") {
      ith_value_entry <- ith_value[[1]]
    } else { # (class, adduct) tibble
      tibble_names <- names(ith_value[[1]])

      tibble_data <- NULL
      for (j in 1:length(ith_value)) {
        tibble_row <- ith_value[[j]] %>% dplyr::as_tibble()
        if (j > 1) {
          tibble_data <- rbind(tibble_data, tibble_row)
        } else {
          tibble_data <- tibble_row
        }
      }

      ith_value_entry <- list(tibble_data)
    }

    params_reformated[params_names[i]] <- ith_value_entry
  }

  params_reformated
}

#' DIMS write search params
#'
#' @description
#' write out search params into json file
#'
#' @param params_file full path of json file to write out DIMS search params.
#' @param search_params formatted DIMS search params
#'
#' @export
DIMS_write_search_params <- function(params_file, search_params) {
  params_json_formatted <- capture.output(cat(jsonlite::toJSON(search_params, pretty = TRUE)))
  file_conn <- file(params_file)
  writeLines(params_json_formatted, file_conn)
  close(file_conn)

  invisible(0)
}

#' DIMS expand sliced lib
#'
#' @description
#' Combine \code{ms2_ranges} tibble with \code{sliced_lib} (list) as a single tibble.
#'
#' @param ms2_ranges
#' ms2 ranges as produced by \code{mzkitcpp::DI_ms2_ranges()}
#'
#' @param sliced_lib
#' sliced library as produced by \code{mzkitcpp::DI_ms2_ranges()}
#'
#' @export
DIMS_expand_sliced_lib <- function(ms2_ranges, sliced_lib) {
  expanded_sliced_lib <- NULL

  lib_names <- names(sliced_lib)

  for (i in 1:length(sliced_lib)) {
    window_id <- as.integer(lib_names[[i]])
    data_slice <- sliced_lib[[i]]

    data_expanded <- cbind(data_slice, precursor_range_id = rep(window_id, nrow(data_slice)))

    window_data <- ms2_ranges %>% dplyr::filter(precursor_range_id == window_id)

    expanded_slice_lib_I <- data_expanded %>%
      dplyr::inner_join(window_data, by = c("precursor_range_id"))

    if (is.null(expanded_sliced_lib)) {
      expanded_sliced_lib <- expanded_slice_lib_I
    } else {
      expanded_sliced_lib <- rbind(expanded_sliced_lib, expanded_slice_lib_I)
    }
  }

  # handle -1 case
  if ("-1" %in% lib_names) {
    neg_1_data <- sliced_lib$`-1`
    neg_1_window <- tibble::tibble(
      precursor_range_id = -1,
      prec_min_mz = NA,
      prec_max_mz = NA,
      scan_min_mz = NA,
      scan_max_mz = NA
    )

    neg_1_data_expanded <- cbind(neg_1_data,
      precursor_range_id = rep(-1, nrow(neg_1_data))
    )

    neg_1_slice <- dplyr::inner_join(neg_1_data_expanded, neg_1_window, by = c("precursor_range_id"))

    if (is.null(expanded_sliced_lib)) {
      expanded_sliced_lib <- neg_1_slice
    } else {
      expanded_sliced_lib <- rbind(expanded_sliced_lib, neg_1_slice)
    }
  }

  if (!is.null(expanded_sliced_lib)) {
    expanded_sliced_lib <- expanded_sliced_lib %>%
      dplyr::arrange(precursor_range_id, ref_ms1_mz, ref_ms2_mz)
  }

  return(expanded_sliced_lib)
}
